In [1]:
import ast
import requests
import json
import pandas as pd
import re
from urllib.request import Request, urlopen
import urllib.request
from selenium import webdriver
from selenium.webdriver import Chrome
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By 
from selenium.webdriver.support.ui import WebDriverWait 
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.options import Options
import numpy as np

In [2]:
# Activation of Chrome Options

chrome_options = Options()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')

#mettre le bon chemin 
driver = webdriver.Chrome("chromedriver",chrome_options=chrome_options) 

#recupérer la page web
driver.get("https://www.persee.fr/search?q=fuite+des+cerveaux+europe&ta=article")

/home/biglifa/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: DeprecationWarning: use options instead of chrome_options
  if __name__ == '__main__':

In [3]:
#récupérerer le nombre d'articles
nb_resulats = driver.find_elements_by_class_name("result-count")[0].text
nb_resulats = int(nb_resulats[0:6])

data = pd.DataFrame(index=list(np.arange(nb_resulats)),
    columns=['Title','Context','Year_publication','Collection','Authors','Role','Document_issue','Page_issue'])

data.head()

,Title,Context,Year_publication,Collection,Authors,Role,Document_issue,Page_issue
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
docs=driver.find_elements_by_class_name("doc-result")

i=0
for doc in docs: 
    #Title
    title=doc.find_elements_by_class_name("title")[0].text
    
    #author
    author=[a.text for a in doc.find_elements_by_class_name("picto")]
    author=str(author)[1:-1]
    
    #Role
    role=''
    try: 
        role=doc.find_element_by_class_name("role").text[1:-1]
    except:
        role=''
        pass
            
    
    #Collection
    collection=doc.find_element_by_class_name("collection").text 
    
    #Date
    date=doc.find_element_by_class_name("documentYear").text[5:]
    
    
    #Document issue
    docIssu=doc.find_element_by_class_name("documentIssue").text
    
    
    #Page issue
    page=doc.find_element_by_class_name("documentPageRange").text[3:]

    #context
    context=doc.find_element_by_class_name("searchContext").text
    
    data.loc[i,:]=[title,context,date,collection,author,role,docIssu,page]
    i+=1
data.head(20)

,Title,Context,Year_publication,Collection,Authors,Role,Document_issue,Page_issue
0,La fuite des cerveaux : le cas de l'ex-URSS,La fuite des cerveaux : le cas de l'ex-URSS......,1992,Hommes et Migrations,"'Andrei Kortunov', 'Rachel Bouyssou'",Traducteur,1155,22-25
1,Que nous devons-nous les uns aux autres ? Le c...,La fuite des cerveaux est-elle un phénomène in...,2008,Revue Philosophique de Louvain,'Stéphane Chauvier',,106-4,771-796
2,"Croissance, redistribution et inégalités dans ...","Croissance, redistribution et inégalités dans ...",1999,Revue économique,"'Frédéric Docquier', 'Hillel Rapoport'",,50-3,499-510
3,Au-delà de la « fuite des cerveaux » : la mobi...,Au-delà de la « fuite des cerveaux » : la mobi...,1997,Revue européenne des migrations internationales,"'Félicitas Hillmann', 'Hedwig Rudolph'",,13-1,71-94
4,Chorafas Dimitri N. — La fuite des cerveaux. L...,Chorafas Dimitri N. — La fuite des cerveaux. L...,1970,Population,'J-N B',,25-5,1131-1132
5,"Migration des Africains diplômés. ""Brain drain...","La question de la ""fuite des cerveaux"" - ou br...",2008,Hommes et Migrations,'Kinuthia Macharia',,1272,126-131
6,Migration Sud-Nord et commerce : une revue de ...,des externalités fiscales induites par l'impos...,2000,Revue d'économie du développement,'M. SCHIFF',,8-3,3-54
7,L'exode des cerveaux vers les États-Unis. Un c...,L'exode des cerveaux vers les États-Unis. Un c...,1973,Revue Tiers Monde,'Enrique Oteiza',,55,515-540
8,"Mobilité et transferts de savoir : acteurs, ré...",Le «drainage des cerveaux» est devenu une ques...,2004,Bulletin de l'Association de Géographes Français,'Sylvie Daviet',,81-2,162-172
9,L'exode des cerveaux,"L'exode des cerveaux...L'EXODE DES CERVEAUX U,...",1972,Revue économique,'Robert Lacroix',,23-1,54-69
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
#Tranformer en dataframe
data.to_csv(index = True, sep=',', path_or_buf='data.csv')

In [6]:
#Problème cela ne recupère que 10 articles